# Generated by Django 2.2.11 on 2022-01-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='image_file_path',
        ),
    ]
